/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdvertiseIndexRouteImport } from './routes/advertise/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppEarningsRouteImport } from './routes/app/earnings'
import { Route as AppPayoutRouteImport } from './routes/app/payout'
import { Route as AppSignupRouteImport } from './routes/app/signup'
import { Route as AppWatchRouteImport } from './routes/app/watch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseIndexRoute = AdvertiseIndexRouteImport.update({
  id: '/advertise/',
  path: '/advertise/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEarningsRoute = AppEarningsRouteImport.update({
  id: '/app/earnings',
  path: '/app/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPayoutRoute = AppPayoutRouteImport.update({
  id: '/app/payout',
  path: '/app/payout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSignupRoute = AppSignupRouteImport.update({
  id: '/app/signup',
  path: '/app/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWatchRoute = AppWatchRouteImport.update({
  id: '/app/watch',
  path: '/app/watch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/earnings': typeof AppEarningsRoute
  '/app/payout': typeof AppPayoutRoute
  '/app/signup': typeof AppSignupRoute
  '/app/watch': typeof AppWatchRoute
  '/admin/': typeof AdminIndexRoute
  '/advertise/': typeof AdvertiseIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/earnings': typeof AppEarningsRoute
  '/app/payout': typeof AppPayoutRoute
  '/app/signup': typeof AppSignupRoute
  '/app/watch': typeof AppWatchRoute
  '/admin': typeof AdminIndexRoute
  '/advertise': typeof AdvertiseIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/earnings': typeof AppEarningsRoute
  '/app/payout': typeof AppPayoutRoute
  '/app/signup': typeof AppSignupRoute
  '/app/watch': typeof AppWatchRoute
  '/admin/': typeof AdminIndexRoute
  '/advertise/': typeof AdvertiseIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/earnings'
    | '/app/payout'
    | '/app/signup'
    | '/app/watch'
    | '/admin/'
    | '/advertise/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/earnings'
    | '/app/payout'
    | '/app/signup'
    | '/app/watch'
    | '/admin'
    | '/advertise'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app/earnings'
    | '/app/payout'
    | '/app/signup'
    | '/app/watch'
    | '/admin/'
    | '/advertise/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppEarningsRoute: typeof AppEarningsRoute
  AppPayoutRoute: typeof AppPayoutRoute
  AppSignupRoute: typeof AppSignupRoute
  AppWatchRoute: typeof AppWatchRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdvertiseIndexRoute: typeof AdvertiseIndexRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise/': {
      id: '/advertise/'
      path: '/advertise'
      fullPath: '/advertise/'
      preLoaderRoute: typeof AdvertiseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/earnings': {
      id: '/app/earnings'
      path: '/app/earnings'
      fullPath: '/app/earnings'
      preLoaderRoute: typeof AppEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/payout': {
      id: '/app/payout'
      path: '/app/payout'
      fullPath: '/app/payout'
      preLoaderRoute: typeof AppPayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/signup': {
      id: '/app/signup'
      path: '/app/signup'
      fullPath: '/app/signup'
      preLoaderRoute: typeof AppSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/watch': {
      id: '/app/watch'
      path: '/app/watch'
      fullPath: '/app/watch'
      preLoaderRoute: typeof AppWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppEarningsRoute: AppEarningsRoute,
  AppPayoutRoute: AppPayoutRoute,
  AppSignupRoute: AppSignupRoute,
  AppWatchRoute: AppWatchRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdvertiseIndexRoute: AdvertiseIndexRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
